const NAME_OR_PASSWORD_IS_REQUIRED='用户名或者密码不能为空'
const USER_ALREADY_EXISTS='用户已经存在'
const USER_DOES_NOT_EXIST='用户名不存在'
const PASSWORD_INCORRECT='密码错误'
const UNAUTHORIZED='认证失败'

module.exports = {
    NAME_OR_PASSWORD_IS_REQUIRED,
    USER_ALREADY_EXISTS,
    USER_DOES_NOT_EXIST,
    PASSWORD_INCORRECT,
    UNAUTHORIZED
}
